[project]
site_name = "Python Project Template Docs"

markdown_extensions = [
    "admonition",
    "pymdownx.details",
    "pymdownx.superfences",
    "pymdownx.highlight",
    "pymdownx.inlinehilite",
    "pymdownx.tabbed",
    "pymdownx.magiclink"
]

[project.plugins.mkdocstrings]
default_handler = "python"

[project.plugins.mkdocstrings.handlers.python]
paths = ["."]

[project.plugins.mkdocstrings.handlers.python.options]
show_root_heading = true
show_source = true
heading_level = 2
show_signature_annotations = true

# Activating the HTML validation engine safely via TOML table definitions
[project.plugins.htmlproofer]
